"""Generate the auto-reference doc pages from the registry + recipes.

Produces:
  docs/reference/tools.md    — every tool YAML grouped by category
  docs/reference/recipes.md  — every registered recipe + its DAG

Run before `mkdocs build` (the docs CI workflow does this).  Re-running
keeps the docs in sync with the registry without hand-editing.

    python scripts/gen_docs.py
"""
from __future__ import annotations

import json
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS_DIR = REPO_ROOT / "registry" / "tools"
OUT_DIR = REPO_ROOT / "docs" / "reference"
README = REPO_ROOT / "README.md"
CITES_JSON = REPO_ROOT / "registry" / "tool_citations.json"

# README section regenerated in place between these markers.
README_START = "<!-- TOOLS-TABLE:START -->"
README_END = "<!-- TOOLS-TABLE:END -->"


def _load_citations() -> "tuple[dict, dict | None]":
    """Return (tool_id → {total, recent, category, pmid}, recent_window) from the
    cached ``registry/tool_citations.json``, or ({}, None) if it isn't there —
    the citation columns are additive, so docs still generate without it."""
    if not CITES_JSON.exists():
        return {}, None
    data = json.loads(CITES_JSON.read_text(encoding="utf-8"))
    return data.get("tools", {}), data.get("recent_window")


def _fmt_cites(n: object) -> str:
    return f"{n:,}" if isinstance(n, int) else "n/a"


def _window_label(window: "dict | None") -> str:
    return f"{window['start']}–{window['end']}" if window else "recent"


def _leaderboard(cites: dict, window: "dict | None", *, top: int, level: str) -> str:
    """Markdown 'most-used tools' table, ranked by recent citations."""
    ranked = sorted(
        ((tid, c) for tid, c in cites.items() if isinstance(c.get("recent"), int)),
        key=lambda kv: kv[1]["recent"], reverse=True,
    )[:top]
    if not ranked:
        return ""
    w = _window_label(window)
    yrs = window["years"] if window else 5
    lines = [
        f"{level} Most-used tools · citations in {w}",
        "",
        "Ranked by how many papers cited each tool's canonical reference in the "
        f"last {yrs} full years — a rough proxy for *current* adoption. Counts "
        "are a lower bound on real use (not everyone cites), and older tools have "
        "had longer to accrue totals. Source: Europe PMC.",
        "",
        f"| # | Tool | Category | Cites {w} | Total |",
        "|--:|---|---|--:|--:|",
    ]
    for i, (tid, c) in enumerate(ranked, 1):
        lines.append(
            f"| {i} | `{tid}` | {c.get('category', '')} | "
            f"{_fmt_cites(c.get('recent'))} | {_fmt_cites(c.get('total'))} |"
        )
    lines.append("")
    return "\n".join(lines)


def _load_by_cat() -> "dict[str, list[dict]]":
    by_cat: dict[str, list[dict]] = {}
    for p in sorted(TOOLS_DIR.rglob("*.yaml")):
        d = yaml.safe_load(p.read_text(encoding="utf-8"))
        by_cat.setdefault(d.get("category", "uncategorized"), []).append(d)
    return by_cat


def gen_readme_block() -> str:
    """Compact category-summary table for the README (full list lives in
    docs/reference/tools.md)."""
    by_cat = _load_by_cat()
    total = sum(len(v) for v in by_cat.values())
    lines = [
        README_START,
        "<!-- Auto-generated by scripts/gen_docs.py — do not edit by hand. -->",
        "",
        f"**{total} tools** across **{len(by_cat)} categories**.  Full catalog "
        "with versions, images, and citations: "
        "[docs/reference/tools.md](docs/reference/tools.md).",
        "",
        "| Category | # | Examples |",
        "|---|--:|---|",
    ]
    for cat in sorted(by_cat):
        tools = sorted(by_cat[cat], key=lambda d: d["id"])
        ex = ", ".join(f"`{t['id']}`" for t in tools[:4])
        if len(tools) > 4:
            ex += ", …"
        lines.append(f"| {cat} | {len(tools)} | {ex} |")
    cites, window = _load_citations()
    lb = _leaderboard(cites, window, top=10, level="###") if cites else ""
    if lb:
        lines += ["", lb.rstrip(),
                  "Full per-tool counts: "
                  "[docs/reference/tools.md](docs/reference/tools.md)."]
    lines += ["", README_END]
    return "\n".join(lines)


def update_readme() -> bool:
    """Rewrite the README tools table between the markers.  Returns True if the
    file changed."""
    text = README.read_text(encoding="utf-8")
    if README_START not in text or README_END not in text:
        print(f"README markers not found in {README}; skipping tools table.")
        return False
    pre = text.split(README_START)[0]
    post = text.split(README_END, 1)[1]
    new = pre + gen_readme_block() + post
    if new != text:
        README.write_text(new, encoding="utf-8")
        print(f"Updated {README} tools table.")
        return True
    print(f"{README} tools table already current.")
    return False


def gen_tools() -> str:
    by_cat = _load_by_cat()
    cites, window = _load_citations()
    total = sum(len(v) for v in by_cat.values())
    lines = [
        "# Tools",
        "",
        f"**{total} tools** across {len(by_cat)} categories, all pulled as "
        "BioContainer / public images on first use.  This page is "
        "auto-generated from `registry/tools/` by `scripts/gen_docs.py`.",
        "",
    ]
    lb = _leaderboard(cites, window, top=15, level="##") if cites else ""
    if lb:
        lines += [lb]
    wlab = _window_label(window)
    for cat in sorted(by_cat):
        tools = sorted(by_cat[cat], key=lambda d: d["id"])
        lines.append(f"## {cat}  ({len(tools)})")
        lines.append("")
        if cites:
            lines.append(f"| Tool | Version | Image | Citation | Total cites | Cites {wlab} |")
            lines.append("|---|---|---|---|--:|--:|")
        else:
            lines.append("| Tool | Version | Image | Citation |")
            lines.append("|---|---|---|---|")
        for d in tools:
            dep = " ⚠️ deprecated" if d.get("deprecated") else ""
            img = d.get("container", {}).get("image", "")
            cit = d.get("citation", "").replace("|", "/")
            row = (
                f"| `{d['id']}`{dep} | {d.get('version','')} | "
                f"`{img}` | {cit} |"
            )
            if cites:
                c = cites.get(d["id"], {})
                row += f" {_fmt_cites(c.get('total'))} | {_fmt_cites(c.get('recent'))} |"
            lines.append(row)
        lines.append("")
    return "\n".join(lines) + "\n"


def gen_recipes() -> str:
    # Import after sys.path is set by running from repo root
    import sys
    sys.path.insert(0, str(REPO_ROOT))
    from bioflow.recipes import get, names  # noqa: PLC0415

    lines = [
        "# Recipes",
        "",
        f"**{len(names())} recipes**, each invokable as "
        "`bioflow recipe run <name> [options]`.  Auto-generated from the "
        "recipe registry by `scripts/gen_docs.py`.",
        "",
    ]
    for name in sorted(names()):
        pipe = get(name)
        lines.append(f"## `{name}`")
        lines.append("")
        lines.append(f"{pipe.description}")
        lines.append("")
        try:
            plan = pipe.dry_run()
            lines.append(f"*{plan['n_stages']} stage(s):*")
            lines.append("")
            for s in plan["stages"]:
                lines.append(f"- **{s['name']}** — `{s.get('image','')}`")
            lines.append("")
        except Exception:
            lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "tools.md").write_text(gen_tools(), encoding="utf-8")
    (OUT_DIR / "recipes.md").write_text(gen_recipes(), encoding="utf-8")
    print(f"Wrote {OUT_DIR / 'tools.md'}")
    print(f"Wrote {OUT_DIR / 'recipes.md'}")
    update_readme()


if __name__ == "__main__":
    main()
