"""Hand-written counts in the docs must match the registry.

The auto-generated blocks (`docs/reference/tools.md`) are regenerated by
`scripts/gen_docs.py` and stay correct on their own. The prose around them is
written by hand, and it had drifted badly — README claimed "113 tools" in one
place and "58 tools" in another while docs/index.md said "110", against an
actual 137. A reader has no way to tell which number to trust.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
TOOLS_DIR = REPO_ROOT / "registry" / "tools"


def _actual() -> "tuple[int, int]":
    yamls = list(TOOLS_DIR.rglob("*.yaml"))
    return len(yamls), len({p.parent.name for p in yamls})


@pytest.mark.parametrize("doc", ["README.md", "docs/index.md"])
def test_tool_counts_in_prose_match_the_registry(doc):
    n_tools, n_cats = _actual()
    text = (REPO_ROOT / doc).read_text(encoding="utf-8")

    claimed = {int(m) for m in re.findall(r"\*\*(\d+) tools\*\*", text)}
    claimed |= {int(m) for m in re.findall(r"(\d+) tools in \d+ categories", text)}
    wrong = sorted(c for c in claimed if c != n_tools)
    assert not wrong, (
        f"{doc} claims {wrong} tools; the registry holds {n_tools}. "
        "Update the prose (the generated tables refresh themselves)."
    )


@pytest.mark.parametrize("doc", ["README.md", "docs/index.md"])
def test_category_counts_in_prose_match_the_registry(doc):
    _n_tools, n_cats = _actual()
    text = (REPO_ROOT / doc).read_text(encoding="utf-8")
    claimed = {int(m) for m in re.findall(r"across (\d+) categories", text)}
    claimed |= {int(m) for m in re.findall(r"tools in (\d+) categories", text)}
    wrong = sorted(c for c in claimed if c != n_cats)
    assert not wrong, (
        f"{doc} claims {wrong} categories; the registry has {n_cats}."
    )


def test_recipe_count_in_prose_matches_the_registry():
    from bioflow.recipes import names

    n = len(names())
    text = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
    claimed = {int(m) for m in re.findall(r"\*\*(\d+) recipes\*\*", text)}
    wrong = sorted(c for c in claimed if c != n)
    assert not wrong, f"README claims {wrong} recipes; {n} are registered."
